version: '3'


services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: blood-donation
    ports:
      - '5430:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usr" ]
      interval: 10s
      timeout: 5s
      retries: 3

  blood-donation-system:
    build:
      context: ./blood-donation-system
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/blood-donation
      spring.datasource.username: usr
      spring.datasource.password: pwd
      management.endpoints.web.exposure.include: health
      management.endpoint.health.show-details: never
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
